### ISSUE TITLE
Abandon all hope

### ISSUE THREAD

**Issue by NoOne2246** [jhuangmystery/btReader#11]
remove abandoned ~~books~~ chapters

This is the most important part.

**Comment by jhuangmystery** [comment]
Abandoned books? As long as they are on the site, I feel like removing them is quite pointless... (Also, it might be an issue to try and work into the program, because there is nothing that really tells us that a project has been abandoned)

If this is about novels that have been removed from the site because of the Copyright issues, it's already there.

**Comment by NoOne2246** [comment]
first line of pared text will have:
{{Template:Abandoned}}
which will indicate abandonment.

**Comment by jhuangmystery** [comment]
I'm not sure what you mean by this...? Where would this come up as a Copyright issue? if there is a copyright claim, the whole page would be removed from the novel list, not just one chapter. Also, abandoned projects are still there, it's just the fact that nobody is TLing it...?

**Comment by NoOne2246** [comment]
welp it seems that this was resolved ages ago
